name = "frederico-theophilo-neto"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NEXT_PUBLIC_SANITY_PROJECT_ID = "qasd0k09"
NEXT_PUBLIC_SANITY_DATASET = "production"
